### ISSUE TITLE
TODO LIST: Some built-in helper functions

### ISSUE THREAD

**Issue by GaZ3ll3** [GaZ3ll3/femex#12]
In PDEcs module,

there should be some functions like:

- [x] Integral over boundary
    - [x] Specifiy all boundary or part of boundary
- [x] Integral over domain
    - [x] Domain still *cannot* specify sub-domains
- [x] Solver specification
    - [x] Use ``umfpack``
    - [x] Use ``AMG`` as preconditioner
        - Usually, it will be slower if matrix size is not large, in Matlab, there is no way to run a huge matrix, anyway.

- [x] Extract Neumann data
- [x] Extract Dirichlet data (however, this is not necessary)

- [ ] Regularization terms 
    - [ ] Total variation 
    - [ ] Tikhonov 
    - [ ] TSVD
    - [ ] Iterative

- [x] Gradient for the regularization terms
- [ ] Objective function evaluation expenses estimate

**Comment by GaZ3ll3** [comment]
working on regularization.
